FROM rustembedded/cross:arm-unknown-linux-gnueabihf

RUN echo 'deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ xenial main multiverse restricted universe' >> /etc/apt/sources.list && \
    echo 'deb [arch=armhf] http://ports.ubuntu.com/ubuntu-ports/ xenial-updates main multiverse restricted universe' >> /etc/apt/sources.list && \
    dpkg --add-architecture armhf && \
    apt-get update && \
    apt-get install -y \
        libavahi-compat-libdnssd-dev:armhf \
        libavahi-compat-libdnssd1:armhf \
        libavahi-client-dev:armhf

ENV PKG_CONFIG_LIBDIR=/usr/lib/arm-linux-gnueabihf/pkgconfig \
    LD_LIBRARY_PATH=/usr/lib/arm-linux-gnueabihf
